version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: subete
      RABBITMQ_DEFAULT_PASS: subete@321